[podcast]
ID = "p_sine"
Title = "Sinewaves"
Subtitle = "Only pure sines"
Author = "Sine Master"
Description = "Only pure sine waves here."
Copyright = "Sine Master, 2008-2024"
Category = "Arts"
Language = "en"
CoverURI = "urn:orchard:iid:91815d6580766720d4c6c2fac4b983808eb5e6308860e258b994a6149033b8b2"

[[episodes]]
ID = "e_vxWvbNvj2lw"
Title = "Pink Noise - II"
Subtitle = "Pink. Take two."
Author = "Sine Master"
PubDate = 2024-06-17T18:11:04
Description = "This is 220 Hz. Again."
DurationSecs = 60
MediaURI = "urn:orchard:mid:c33bcc84-59d4-4a48-a24e-6c940350ed37"
CoverURI = ""
Explicit = false

[[episodes]]
ID = "e_gnPgu9R5ZRk"
Title = "220 Hz"
Subtitle = "Pure 220 Hz sine wave."
Author = "Sine Master"
PubDate = 2023-06-16T17:00:00
Description = "This is 220 Hz"
DurationSecs = 300
MediaURI = "urn:orchard:mid:552a40ff43a539119df32f8aab534ec81d8b5ebf2cce2fe73c8d8ba6d4f7b781"
CoverURI = ""
Explicit = false

[[episodes]]
ID = "e_TTdHrnn6WJ8"
Title = "440 Hz"
Subtitle = "Pure 440 Hz sine wave."
Author = "Sine Master"
PubDate = 2023-06-15T08:00:00
Description = "This is 440 Hz"
DurationSecs = 300
MediaURI = "urn:orchard:mid:f4ef6b0d117fa6ad65f2029d34a0191ecc4bfbd6dfdfa7420202362be011c6d7"
CoverURI = ""
Explicit = false
